---
- name: set ulimits
  pam_limits:
    domain: '{{ item.domain }}'
    limit_type: '{{ item.limit_type }}'
    limit_item: '{{ item.limit_item }}'
    value: '{{ item.value }}'
  with_items: '{{ ulimit_config }}'
